# Generated by Django 5.0.2 on 2024-02-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=10, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('runtime', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.TextField()),
                ('actors', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('imdb_id', models.CharField(max_length=20)),
                ('imdb_votes', models.CharField(max_length=20)),
                ('movie_type', models.CharField(max_length=20)),
                ('dvd', models.DateField(blank=True, null=True)),
                ('box_office', models.CharField(max_length=500)),
                ('production', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='movie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
