# Generated by Django 5.0.2 on 2024-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='meta_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
